apiVersion:  v1
kind: ConfigMap
metadata:
  name: healthcheckconfig
data:
  health.applicationlist: audit-il-audit-services,outward-il-outward-channel-service,outwardsoap-il-outward-channel-service-soap
  health.namespace.value: insulationlayer
  health.application.criteria: percentage
  health.servicelist: ${SERVICE_LIST_WITH_FLAG:{'audit-il-audit-services':'N','outward-il-outward-channel-service':'Y','outwardsoap-il-outward-channel-service-soap':'Y'}}
  spring.kafka.bootstrap-servers: 98.70.50.3:9092
  spring.kafka.consumer.auto-offset-reset: latest
  spring.kafka.consumer.group-id: my-group
  spring.kafka.consumer.key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  spring.kafka.consumer.value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  spring.kafka.consumer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
  spring.kafka.consumer.value-serializer: org.apache.kafka.common.serialization.StringSerializer
  management.endpoint.health.show-details: always
  management.endpoints.web.exposure.include:  health,info
  spring.datasource.url: jdbc:postgresql://74.225.160.55:5433/il-outward-gcp-poc-db
  spring.datasource.username: yugabyte
  spring.datasource.password: Ybdbazureecifpoc@123$
  spring.datasource.driver-class-name: org.postgresql.Driver
  spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  





