apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: insulationlayer
  name: service-reader
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]